@ignore_exception()
def func():
    raise ValueError
  
try:    
    func()
except Exception as error:
    print(type(error))