Во время записи в файл было возбуждено исключение ValueError
Тень от руин нависает над вами, наполняя вас решительностью